<?php ob_start(); ?>
<?php $fieldError = static fn (string $field): string => isset($errors[$field]) ? ' has-error' : ''; ?>
<section class="page-header"><div><p class="eyebrow">Planning</p><h2>Creer une reservation</h2><p class="muted">Planifiez l'utilisation d'une salle active.</p></div></section>
<form method="post" action="/reservations/store" class="form-card" novalidate>
	<?= csrf_field() ?>
	<div class="form-group<?= $fieldError('salle_id') ?>"><label for="salle_id">Salle</label><select id="salle_id" name="salle_id" required><option value="">Selectionner une salle</option><?php foreach ($salles as $salle): ?><option value="<?= (int) $salle->id ?>" <?= (string) ($old['salle_id'] ?? '') === (string) $salle->id ? 'selected' : '' ?>><?= htmlspecialchars($salle->nom) ?> - <?= (int) $salle->capacite ?> places</option><?php endforeach; ?></select><span class="field-error"><?= htmlspecialchars($errors['salle_id'] ?? '') ?></span></div>
	<div class="form-grid"><div class="form-group<?= $fieldError('responsable') ?>"><label for="responsable">Responsable</label><input id="responsable" name="responsable" value="<?= htmlspecialchars($old['responsable'] ?? '') ?>" required maxlength="120"><span class="field-error"><?= htmlspecialchars($errors['responsable'] ?? '') ?></span></div><div class="form-group<?= $fieldError('email') ?>"><label for="email">Adresse e-mail</label><input id="email" name="email" value="<?= htmlspecialchars($old['email'] ?? '') ?>" type="email" required maxlength="190"><span class="field-error"><?= htmlspecialchars($errors['email'] ?? '') ?></span></div></div>
	<div class="form-group<?= $fieldError('motif') ?>"><label for="motif">Motif</label><input id="motif" name="motif" value="<?= htmlspecialchars($old['motif'] ?? '') ?>" required maxlength="255"><span class="field-error"><?= htmlspecialchars($errors['motif'] ?? '') ?></span></div>
	<div class="form-grid"><div class="form-group<?= $fieldError('date_debut') ?>"><label for="date_debut">Debut</label><input id="date_debut" name="date_debut" value="<?= htmlspecialchars($old['date_debut'] ?? '') ?>" type="datetime-local" required><span class="field-error"><?= htmlspecialchars($errors['date_debut'] ?? '') ?></span></div><div class="form-group<?= $fieldError('date_fin') ?>"><label for="date_fin">Fin</label><input id="date_fin" name="date_fin" value="<?= htmlspecialchars($old['date_fin'] ?? '') ?>" type="datetime-local" required><span class="field-error"><?= htmlspecialchars($errors['date_fin'] ?? '') ?></span></div></div>
	<div class="form-actions"><a class="btn btn-secondary" href="/reservations">Annuler</a><button class="btn btn-primary" type="submit">Enregistrer la reservation</button></div>
</form>
<?php $content = ob_get_clean(); require dirname(__DIR__) . '/layout.php'; ?>
